language: node_js
node_js:
  - "8"
notifications:
    email:
        recipients:
            - ta7382@gmail.com
        on_failure: always
libinstall:
    - npm install -g @angular/cli
    - npm install
script:
    - npm start